intro:
  target: dev
  outputs:
    dev:
      type: mariadb
      server: localhost
      port: 3306
      schema: intro
      username: root
      password: mariadb
      driver: MySQL ODBC 8.0 ANSI Driver
